name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile PRISMA Flow Diagram
        working-directory: ./chapters/SLR
        uses: xu-cheng/latex-action@v2
        with:
          root_file: prisma_diagram.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex 
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: thesis.pdf
